const mongoose=require("mongoose");
const Conversation=require("../../models/Conversation");
const ConversationLabel=require("../../models/ConversationLabel");
const MAX_PINNED_CONVERSATIONS=5;
const SYSTEM_LABELS=[
{name:"Compra",slug:"compra",color:"#22c55e",icon:"shopping-bag"},
{name:"Venta",slug:"venta",color:"#3b82f6",icon:"store"},
{name:"Soporte",slug:"soporte",color:"#8b5cf6",icon:"headphones"},
{name:"Disputa",slug:"disputa",color:"#ef4444",icon:"shield-alert"},
{name:"Pago",slug:"pago",color:"#14b8a6",icon:"credit-card"},
{name:"Entrega",slug:"entrega",color:"#f59e0b",icon:"truck"},
{name:"Reembolso",slug:"reembolso",color:"#ec4899",icon:"rotate-ccw"},
{name:"Urgente",slug:"urgente",color:"#f97316",icon:"siren"},
{name:"IA",slug:"ia",color:"#06b6d4",icon:"bot"},
{name:"Riesgo Alto",slug:"riesgo-alto",color:"#dc2626",icon:"triangle-alert"}
];
function id(v){return String(v?._id||v?.user||v||"");}
function bad(msg,code=400){const e=new Error(msg);e.statusCode=code;throw e;}
function assertId(v,n){if(!mongoose.Types.ObjectId.isValid(String(v||"")))bad(`${n} inválido.`);}
function participant(c,u){return (c.participants||[]).some(x=>id(x)===String(u));}
async function getConversationForUser(conversationId,userId){assertId(conversationId,"conversationId");const c=await Conversation.findById(conversationId);if(!c)bad("Conversación no encontrada.",404);if(!participant(c,userId))bad("No tienes acceso a esta conversación.",403);return c;}
async function ensureSystemLabels(){const ops=SYSTEM_LABELS.map(label=>({updateOne:{filter:{slug:label.slug,owner:null},update:{$setOnInsert:{...label,isSystem:true,owner:null,isActive:true}},upsert:true}}));await ConversationLabel.bulkWrite(ops,{ordered:false});return ConversationLabel.find({isSystem:true,owner:null,isActive:true}).sort({name:1});}
async function toggleFavorite({conversationId,userId,enabled}){const c=await getConversationForUser(conversationId,userId);const exists=(c.favoriteBy||[]).some(x=>id(x)===String(userId));const on=typeof enabled==="boolean"?enabled:!exists;if(on&&!exists)c.favoriteBy.push(userId);if(!on&&exists)c.favoriteBy=c.favoriteBy.filter(x=>id(x)!==String(userId));c.organizationAudit=c.organizationAudit||{};c.organizationAudit.lastFavoriteAt=new Date();await c.save();return {conversation:c,favorite:on};}
async function pinConversation({conversationId,userId}){const c=await getConversationForUser(conversationId,userId);const existing=(c.pinnedBy||[]).find(x=>id(x.user)===String(userId));if(existing)return {conversation:c,pinned:true,order:existing.order};const count=await Conversation.countDocuments({participants:userId,"pinnedBy.user":userId});if(count>=MAX_PINNED_CONVERSATIONS)bad(`Solo puedes fijar ${MAX_PINNED_CONVERSATIONS} conversaciones.`,409);c.pinnedBy.push({user:userId,order:count+1,pinnedAt:new Date()});c.organizationAudit=c.organizationAudit||{};c.organizationAudit.lastPinnedAt=new Date();await c.save();return {conversation:c,pinned:true,order:count+1};}
async function unpinConversation({conversationId,userId}){const c=await getConversationForUser(conversationId,userId);c.pinnedBy=(c.pinnedBy||[]).filter(x=>id(x.user)!==String(userId));await c.save();return {conversation:c,pinned:false};}
async function reorderPinned({userId,orderedConversationIds=[]}){const ids=[...new Set(orderedConversationIds.map(String))].slice(0,MAX_PINNED_CONVERSATIONS);ids.forEach(x=>assertId(x,"conversationId"));for(let i=0;i<ids.length;i++){const c=await Conversation.findOne({_id:ids[i],participants:userId,"pinnedBy.user":userId});if(!c)continue;const pin=c.pinnedBy.find(x=>id(x.user)===String(userId));if(pin)pin.order=i+1;await c.save();}return Conversation.find({participants:userId,"pinnedBy.user":userId});}
async function archiveConversation({conversationId,userId}){const c=await getConversationForUser(conversationId,userId);if(!(c.archivedBy||[]).some(x=>id(x)===String(userId)))c.archivedBy.push(userId);c.organizationAudit=c.organizationAudit||{};c.organizationAudit.lastArchivedAt=new Date();await c.save();return {conversation:c,archived:true};}
async function restoreConversation({conversationId,userId}){const c=await getConversationForUser(conversationId,userId);c.archivedBy=(c.archivedBy||[]).filter(x=>id(x)!==String(userId));await c.save();return {conversation:c,archived:false};}
async function createCustomLabel({userId,name,color,icon}){const n=String(name||"").trim();if(!n)bad("El nombre de la etiqueta es obligatorio.");const slug=n.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,50);return ConversationLabel.findOneAndUpdate({slug,owner:userId},{$set:{name:n.slice(0,40),color:color||"#8b5cf6",icon:icon||"tag",isSystem:false,owner:userId,isActive:true}},{new:true,upsert:true,setDefaultsOnInsert:true});}
async function updateCustomLabel({labelId,userId,name,color,icon}){assertId(labelId,"labelId");const l=await ConversationLabel.findOne({_id:labelId,owner:userId,isSystem:false});if(!l)bad("Etiqueta personalizada no encontrada.",404);if(name!==undefined)l.name=String(name).trim().slice(0,40);if(color!==undefined)l.color=String(color);if(icon!==undefined)l.icon=String(icon);await l.save();return l;}
async function deleteCustomLabel({labelId,userId}){assertId(labelId,"labelId");const l=await ConversationLabel.findOne({_id:labelId,owner:userId,isSystem:false});if(!l)bad("Etiqueta personalizada no encontrada.",404);await Conversation.updateMany({"labels.label":l._id,"labels.assignedBy":userId},{$pull:{labels:{label:l._id,assignedBy:userId}}});l.isActive=false;await l.save();return l;}
async function listAvailableLabels(userId){await ensureSystemLabels();return ConversationLabel.find({isActive:true,$or:[{isSystem:true,owner:null},{owner:userId}]}).sort({isSystem:-1,name:1});}
async function assignLabel({conversationId,labelId,userId}){assertId(labelId,"labelId");const c=await getConversationForUser(conversationId,userId);const l=await ConversationLabel.findOne({_id:labelId,isActive:true,$or:[{isSystem:true,owner:null},{owner:userId}]});if(!l)bad("Etiqueta no disponible.",404);const exists=(c.labels||[]).some(x=>id(x.label)===String(labelId)&&id(x.assignedBy)===String(userId));if(!exists)c.labels.push({label:labelId,assignedBy:userId,assignedAt:new Date()});await c.save();return {conversation:c,label:l};}
async function removeLabel({conversationId,labelId,userId}){const c=await getConversationForUser(conversationId,userId);c.labels=(c.labels||[]).filter(x=>!(id(x.label)===String(labelId)&&id(x.assignedBy)===String(userId)));await c.save();return {conversation:c,removed:true};}
async function updateCategory({conversationId,userId,category,priority}){const c=await getConversationForUser(conversationId,userId);const cats=["GENERAL","BUY","SELL","SUPPORT","DISPUTE"];const prios=["LOW","NORMAL","HIGH","CRITICAL"];if(category!==undefined){if(!cats.includes(category))bad("Categoría inválida.");c.category=category;c.organizationAudit=c.organizationAudit||{};c.organizationAudit.lastCategoryUpdate=new Date();}if(priority!==undefined){if(!prios.includes(priority))bad("Prioridad inválida.");c.priority=priority;}await c.save();return c;}
async function getOrganizationSummary(userId){const base={participants:userId};const [total,favorites,pinned,archived,highRisk,categories]=await Promise.all([Conversation.countDocuments(base),Conversation.countDocuments({...base,favoriteBy:userId}),Conversation.countDocuments({...base,"pinnedBy.user":userId}),Conversation.countDocuments({...base,archivedBy:userId}),Conversation.countDocuments({...base,priority:{$in:["HIGH","CRITICAL"]}}),Conversation.aggregate([{$match:{participants:new mongoose.Types.ObjectId(userId)}},{$group:{_id:"$category",count:{$sum:1}}}])]);const map=Object.fromEntries(categories.map(x=>[x._id||"GENERAL",x.count]));return {total,favorites,pinned,archived,highRisk,categories:{GENERAL:map.GENERAL||0,BUY:map.BUY||0,SELL:map.SELL||0,SUPPORT:map.SUPPORT||0,DISPUTE:map.DISPUTE||0}};}
module.exports={MAX_PINNED_CONVERSATIONS,SYSTEM_LABELS,ensureSystemLabels,toggleFavorite,pinConversation,unpinConversation,reorderPinned,archiveConversation,restoreConversation,createCustomLabel,updateCustomLabel,deleteCustomLabel,listAvailableLabels,assignLabel,removeLabel,updateCategory,getOrganizationSummary};
